#!/usr/bin/env node
/* =============================================================================
   sync-glass.mjs — vendors @abheet19/glass's base tokens for the static server.

   packages/daemon/public/ is served as-is (no bundler), so a browser-side
   @import needs a same-origin URL, not a bare "node_modules/..." specifier.
   This copies the *real* installed package's src/tokens.css into
   public/glass/vendor/glass-base.css so /glass/tokens.css can `@import` it.

   Nothing here changes what the copy contains. It is byte-identical to
   node_modules/@abheet19/glass/src/tokens.css at install time. If the
   dependency in package.json ever stops resolving, this script fails loudly
   instead of silently serving a stale copy.
   ============================================================================= */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';

const here = dirname(fileURLToPath(import.meta.url));
const require = createRequire(import.meta.url);

let src;
try {
  src = require.resolve('@abheet19/glass/tokens.css');
} catch {
  console.error('sync-glass: @abheet19/glass is not installed — run npm install first.');
  process.exit(1);
}

const destDir = resolve(here, '../public/glass/vendor');
const dest = resolve(destDir, 'glass-base.css');

if (!existsSync(destDir)) mkdirSync(destDir, { recursive: true });

const banner = `/* AUTO-GENERATED by scripts/sync-glass.mjs from @abheet19/glass — do not edit directly. */\n`;
writeFileSync(dest, banner + readFileSync(src, 'utf8'), 'utf8');

console.log(`sync-glass: vendored ${src} -> ${dest}`);
